# Generated by Django 3.1.7 on 2021-09-17 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='birthdate',
            field=models.DateField(default='1980-01-01'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Female', 'female'), ('Transgender', 'Transgender'), ('Male', 'male')], default='Male', max_length=20),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=50, unique=True)),
                ('about', models.CharField(max_length=250, null=True)),
                ('birthdate', models.DateField(default='1980-01-01')),
                ('gender', models.CharField(choices=[('Female', 'female'), ('Transgender', 'Transgender'), ('Male', 'male')], default='Male', max_length=20)),
                ('spec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.doctype')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
