# Generated by Django 3.1.7 on 2021-09-17 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210918_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Transgender', 'Transgender'), ('Female', 'female')], default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Transgender', 'Transgender'), ('Female', 'female')], default='Male', max_length=20),
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.doctor')),
            ],
        ),
    ]
