# Generated by Django 3.1.7 on 2021-09-18 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0004_auto_20210918_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('Female', 'female'), ('Male', 'male'), ('Transgender', 'Transgender')], default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Female', 'female'), ('Male', 'male'), ('Transgender', 'Transgender')], default='Male', max_length=20),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('file1', models.FileField(blank=True, null=True, upload_to='files')),
                ('file2', models.FileField(blank=True, null=True, upload_to='files')),
                ('details', models.CharField(blank=True, max_length=500, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=50, unique=True)),
                ('about', models.CharField(max_length=250, null=True)),
                ('birthdate', models.DateField(default='1980-01-01')),
                ('gender', models.CharField(choices=[('Female', 'female'), ('Male', 'male'), ('Transgender', 'Transgender')], default='Male', max_length=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('O-', 'O-'), ('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('A-', 'A-'), ('AB-', 'AB-'), ('B-', 'B-'), ('AB+', 'AB+')], default='A+', max_length=4)),
                ('PWD', models.BooleanField()),
                ('Remarks', models.CharField(max_length=250)),
                ('weight', models.PositiveIntegerField()),
                ('Address', models.CharField(max_length=250)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.student')),
            ],
        ),
    ]
