# Generated by Django 3.1.7 on 2021-09-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210918_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('AB-', 'AB-'), ('A-', 'A-'), ('AB+', 'AB+'), ('B+', 'B+'), ('O+', 'O+'), ('B-', 'B-'), ('O-', 'O-')], default='A+', max_length=4),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('Transgender', 'Transgender'), ('Male', 'male'), ('Female', 'female')], default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='gender',
            field=models.CharField(choices=[('Transgender', 'Transgender'), ('Male', 'male'), ('Female', 'female')], default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Transgender', 'Transgender'), ('Male', 'male'), ('Female', 'female')], default='Male', max_length=20),
        ),
    ]
