# Generated by Django 3.1.7 on 2021-09-18 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20210918_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='blood_group',
            field=models.CharField(choices=[('A-', 'A-'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O-', 'O-'), ('A+', 'A+'), ('B-', 'B-')], default='A+', max_length=4),
        ),
        migrations.AlterField(
            model_name='bio',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bio', to='webapp.student'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('Transgender', 'Transgender'), ('Female', 'female'), ('Male', 'male')], default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='gender',
            field=models.CharField(choices=[('Transgender', 'Transgender'), ('Female', 'female'), ('Male', 'male')], default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Transgender', 'Transgender'), ('Female', 'female'), ('Male', 'male')], default='Male', max_length=20),
        ),
    ]
